/**
 * Mock trending video data used as a fallback when the YouTube API
 * quota is exceeded (403 error).
 * All videos are in the React / Web Development category.
 */

export interface MockTrendingVideo {
  videoId: string;
  title: string;
  channel: string;
  views: string;
  viewCount: number;
  timeAgo: string;
  thumbnail: string;
  category: string;
  rank: number;
  rating: string;
}

export const MOCK_TRENDING_VIDEOS: MockTrendingVideo[] = [
  {
    videoId: "mock-1",
    title: "React Server Components Explained in 10 Minutes",
    channel: "FIRESHIP",
    views: "1.2M",
    viewCount: 1_200_000,
    timeAgo: "2 weeks ago",
    thumbnail: "https://placehold.co/480x270/16213e/ffffff?text=React+Server+Components",
    category: "React",
    rank: 1,
    rating: "Viral",
  },
  {
    videoId: "mock-2",
    title: "Next.js 15 App Router: Complete Tutorial",
    channel: "LEE ROBINSON",
    views: "890K",
    viewCount: 890_000,
    timeAgo: "1 week ago",
    thumbnail: "https://placehold.co/480x270/1a1a2e/ffffff?text=Next.js+15+Tutorial",
    category: "React",
    rank: 2,
    rating: "Viral",
  },
  {
    videoId: "mock-3",
    title: "Build a Full-Stack App with React and Node.js",
    channel: "TRAVERSY MEDIA",
    views: "750K",
    viewCount: 750_000,
    timeAgo: "3 days ago",
    thumbnail: "https://placehold.co/480x270/0f3460/ffffff?text=Full+Stack+React",
    category: "React",
    rank: 3,
    rating: "Viral",
  },
  {
    videoId: "mock-4",
    title: "The New JavaScript Features You Need to Know in 2026",
    channel: "TRAVERSY MEDIA",
    views: "650K",
    viewCount: 650_000,
    timeAgo: "5 days ago",
    thumbnail: "https://placehold.co/480x270/533483/ffffff?text=JavaScript+2026",
    category: "JavaScript",
    rank: 4,
    rating: "Viral",
  },
  {
    videoId: "mock-5",
    title: "CSS Container Queries Changed Everything",
    channel: "KEVIN POWELL",
    views: "520K",
    viewCount: 520_000,
    timeAgo: "1 week ago",
    thumbnail: "https://placehold.co/480x270/e94560/ffffff?text=CSS+Container+Queries",
    category: "Web Dev",
    rank: 5,
    rating: "Viral",
  },
  {
    videoId: "mock-6",
    title: "React 19 - Every New Feature Explained",
    channel: "JACK HERRINGTON",
    views: "480K",
    viewCount: 480_000,
    timeAgo: "4 days ago",
    thumbnail: "https://placehold.co/480x270/16213e/ffffff?text=React+19+Features",
    category: "React",
    rank: 6,
    rating: "Excellent",
  },
  {
    videoId: "mock-7",
    title: "TypeScript 5.5 - The Features That Matter",
    channel: "MATT POCOCK",
    views: "430K",
    viewCount: 430_000,
    timeAgo: "2 weeks ago",
    thumbnail: "https://placehold.co/480x270/533483/ffffff?text=TypeScript+5.5",
    category: "JavaScript",
    rank: 7,
    rating: "Excellent",
  },
  {
    videoId: "mock-8",
    title: "Building a Design System with Tailwind CSS v4",
    channel: "ADAM WATHAN",
    views: "390K",
    viewCount: 390_000,
    timeAgo: "1 week ago",
    thumbnail: "https://placehold.co/480x270/e94560/ffffff?text=Tailwind+CSS+v4",
    category: "Web Dev",
    rank: 8,
    rating: "Excellent",
  },
  {
    videoId: "mock-9",
    title: "React Hooks Deep Dive - useEffect, useMemo, useCallback",
    channel: "WEB DEV SIMPLIFIED",
    views: "360K",
    viewCount: 360_000,
    timeAgo: "6 days ago",
    thumbnail: "https://placehold.co/480x270/16213e/ffffff?text=React+Hooks+Deep+Dive",
    category: "React",
    rank: 9,
    rating: "Excellent",
  },
  {
    videoId: "mock-10",
    title: "Node.js Backend Architecture - Best Practices",
    channel: "TECH WITH TIM",
    views: "340K",
    viewCount: 340_000,
    timeAgo: "1 week ago",
    thumbnail: "https://placehold.co/480x270/0f3460/ffffff?text=Node.js+Architecture",
    category: "Web Dev",
    rank: 10,
    rating: "Excellent",
  },
  {
    videoId: "mock-11",
    title: "Zustand vs Redux Toolkit - Which State Manager Wins?",
    channel: "THEO",
    views: "310K",
    viewCount: 310_000,
    timeAgo: "3 days ago",
    thumbnail: "https://placehold.co/480x270/16213e/ffffff?text=Zustand+vs+Redux",
    category: "React",
    rank: 11,
    rating: "Excellent",
  },
  {
    videoId: "mock-12",
    title: "Responsive Web Design in 2026 - Modern Approach",
    channel: "KEVIN POWELL",
    views: "290K",
    viewCount: 290_000,
    timeAgo: "5 days ago",
    thumbnail: "https://placehold.co/480x270/e94560/ffffff?text=Responsive+Design+2026",
    category: "Web Dev",
    rank: 12,
    rating: "Excellent",
  },
  {
    videoId: "mock-13",
    title: "JavaScript Closures, Promises, and Async/Await Explained",
    channel: "FIRESHIP",
    views: "270K",
    viewCount: 270_000,
    timeAgo: "2 weeks ago",
    thumbnail: "https://placehold.co/480x270/533483/ffffff?text=JS+Closures+Promises",
    category: "JavaScript",
    rank: 13,
    rating: "Excellent",
  },
  {
    videoId: "mock-14",
    title: "React Testing Library - Complete Guide",
    channel: "JACK HERRINGTON",
    views: "250K",
    viewCount: 250_000,
    timeAgo: "1 week ago",
    thumbnail: "https://placehold.co/480x270/16213e/ffffff?text=React+Testing+Library",
    category: "React",
    rank: 14,
    rating: "Excellent",
  },
  {
    videoId: "mock-15",
    title: "HTML & CSS for Beginners - Full Course 2026",
    channel: "TRAVERSY MEDIA",
    views: "230K",
    viewCount: 230_000,
    timeAgo: "1 week ago",
    thumbnail: "https://placehold.co/480x270/e94560/ffffff?text=HTML+CSS+Full+Course",
    category: "Web Dev",
    rank: 15,
    rating: "Excellent",
  },
  {
    videoId: "mock-16",
    title: "Next.js Middleware and Edge Functions Explained",
    channel: "LEE ROBINSON",
    views: "210K",
    viewCount: 210_000,
    timeAgo: "4 days ago",
    thumbnail: "https://placehold.co/480x270/1a1a2e/ffffff?text=Next.js+Middleware",
    category: "React",
    rank: 16,
    rating: "Excellent",
  },
  {
    videoId: "mock-17",
    title: "Frontend Performance Optimization Masterclass",
    channel: "THEO",
    views: "195K",
    viewCount: 195_000,
    timeAgo: "6 days ago",
    thumbnail: "https://placehold.co/480x270/0f3460/ffffff?text=Frontend+Performance",
    category: "Web Dev",
    rank: 17,
    rating: "Excellent",
  },
  {
    videoId: "mock-18",
    title: "React Native vs Flutter in 2026",
    channel: "FIRESHIP",
    views: "185K",
    viewCount: 185_000,
    timeAgo: "2 weeks ago",
    thumbnail: "https://placehold.co/480x270/16213e/ffffff?text=React+Native+vs+Flutter",
    category: "React",
    rank: 18,
    rating: "Excellent",
  },
  {
    videoId: "mock-19",
    title: "ES2026 JavaScript Features You Should Be Using Now",
    channel: "MATT POCOCK",
    views: "170K",
    viewCount: 170_000,
    timeAgo: "3 days ago",
    thumbnail: "https://placehold.co/480x270/533483/ffffff?text=ES2026+Features",
    category: "JavaScript",
    rank: 19,
    rating: "Excellent",
  },
  {
    videoId: "mock-20",
    title: "GraphQL vs REST - Which API Style to Choose",
    channel: "WEB DEV SIMPLIFIED",
    views: "160K",
    viewCount: 160_000,
    timeAgo: "1 week ago",
    thumbnail: "https://placehold.co/480x270/0f3460/ffffff?text=GraphQL+vs+REST",
    category: "Web Dev",
    rank: 20,
    rating: "Excellent",
  },
  {
    videoId: "mock-21",
    title: "React Suspense and Concurrent Features Deep Dive",
    channel: "JACK HERRINGTON",
    views: "150K",
    viewCount: 150_000,
    timeAgo: "5 days ago",
    thumbnail: "https://placehold.co/480x270/16213e/ffffff?text=React+Suspense",
    category: "React",
    rank: 21,
    rating: "Excellent",
  },
  {
    videoId: "mock-22",
    title: "CSS Grid Layout - Advanced Techniques",
    channel: "KEVIN POWELL",
    views: "140K",
    viewCount: 140_000,
    timeAgo: "2 weeks ago",
    thumbnail: "https://placehold.co/480x270/e94560/ffffff?text=CSS+Grid+Advanced",
    category: "Web Dev",
    rank: 22,
    rating: "Excellent",
  },
  {
    videoId: "mock-23",
    title: "Vite vs Webpack - The Build Tool Showdown",
    channel: "FIRESHIP",
    views: "130K",
    viewCount: 130_000,
    timeAgo: "4 days ago",
    thumbnail: "https://placehold.co/480x270/533483/ffffff?text=Vite+vs+Webpack",
    category: "JavaScript",
    rank: 23,
    rating: "Excellent",
  },
  {
    videoId: "mock-24",
    title: "Authentication in React - JWT, OAuth, and Sessions",
    channel: "WEB DEV SIMPLIFIED",
    views: "125K",
    viewCount: 125_000,
    timeAgo: "1 week ago",
    thumbnail: "https://placehold.co/480x270/16213e/ffffff?text=React+Authentication",
    category: "React",
    rank: 24,
    rating: "Excellent",
  },
  {
    videoId: "mock-25",
    title: "Web Accessibility - A Complete Developer Guide",
    channel: "TRAVERSY MEDIA",
    views: "115K",
    viewCount: 115_000,
    timeAgo: "6 days ago",
    thumbnail: "https://placehold.co/480x270/e94560/ffffff?text=Web+Accessibility",
    category: "Web Dev",
    rank: 25,
    rating: "Excellent",
  },
  {
    videoId: "mock-26",
    title: "React Form Handling - Server Actions vs React Hook Form",
    channel: "THEO",
    views: "108K",
    viewCount: 108_000,
    timeAgo: "3 days ago",
    thumbnail: "https://placehold.co/480x270/16213e/ffffff?text=React+Forms",
    category: "React",
    rank: 26,
    rating: "Excellent",
  },
  {
    videoId: "mock-27",
    title: "Deno 2.0 vs Node.js - Should You Switch?",
    channel: "FIRESHIP",
    views: "102K",
    viewCount: 102_000,
    timeAgo: "2 weeks ago",
    thumbnail: "https://placehold.co/480x270/533483/ffffff?text=Deno+vs+Node",
    category: "JavaScript",
    rank: 27,
    rating: "Excellent",
  },
  {
    videoId: "mock-28",
    title: "Progressive Web Apps - The Complete Guide",
    channel: "TRAVERSY MEDIA",
    views: "95K",
    viewCount: 95_000,
    timeAgo: "1 week ago",
    thumbnail: "https://placehold.co/480x270/e94560/ffffff?text=PWA+Complete+Guide",
    category: "Web Dev",
    rank: 28,
    rating: "Great",
  },
  {
    videoId: "mock-29",
    title: "React Query (TanStack Query) - Practical Tutorial",
    channel: "JACK HERRINGTON",
    views: "89K",
    viewCount: 89_000,
    timeAgo: "5 days ago",
    thumbnail: "https://placehold.co/480x270/16213e/ffffff?text=React+Query+Tutorial",
    category: "React",
    rank: 29,
    rating: "Great",
  },
  {
    videoId: "mock-30",
    title: "Astro Framework - Build Faster Websites",
    channel: "FIRESHIP",
    views: "85K",
    viewCount: 85_000,
    timeAgo: "4 days ago",
    thumbnail: "https://placehold.co/480x270/0f3460/ffffff?text=Astro+Framework",
    category: "Web Dev",
    rank: 30,
    rating: "Great",
  },
  {
    videoId: "mock-31",
    title: "React Compiler - How It Works Under the Hood",
    channel: "MATT POCOCK",
    views: "82K",
    viewCount: 82_000,
    timeAgo: "1 week ago",
    thumbnail: "https://placehold.co/480x270/16213e/ffffff?text=React+Compiler",
    category: "React",
    rank: 31,
    rating: "Great",
  },
  {
    videoId: "mock-32",
    title: "Modern CSS Animations - Scroll-Driven and View Transitions",
    channel: "KEVIN POWELL",
    views: "78K",
    viewCount: 78_000,
    timeAgo: "6 days ago",
    thumbnail: "https://placehold.co/480x270/e94560/ffffff?text=CSS+Animations",
    category: "Web Dev",
    rank: 32,
    rating: "Great",
  },
  {
    videoId: "mock-33",
    title: "JavaScript Design Patterns Every Developer Should Know",
    channel: "WEB DEV SIMPLIFIED",
    views: "74K",
    viewCount: 74_000,
    timeAgo: "2 weeks ago",
    thumbnail: "https://placehold.co/480x270/533483/ffffff?text=JS+Design+Patterns",
    category: "JavaScript",
    rank: 33,
    rating: "Great",
  },
  {
    videoId: "mock-34",
    title: "Remix vs Next.js - React Framework Comparison",
    channel: "THEO",
    views: "70K",
    viewCount: 70_000,
    timeAgo: "3 days ago",
    thumbnail: "https://placehold.co/480x270/16213e/ffffff?text=Remix+vs+Next.js",
    category: "React",
    rank: 34,
    rating: "Great",
  },
  {
    videoId: "mock-35",
    title: "Web Components in 2026 - Are They Worth It?",
    channel: "FIRESHIP",
    views: "65K",
    viewCount: 65_000,
    timeAgo: "1 week ago",
    thumbnail: "https://placehold.co/480x270/e94560/ffffff?text=Web+Components+2026",
    category: "Web Dev",
    rank: 35,
    rating: "Great",
  },
  {
    videoId: "mock-36",
    title: "React Server Functions - The Future of Data Fetching",
    channel: "LEE ROBINSON",
    views: "60K",
    viewCount: 60_000,
    timeAgo: "4 days ago",
    thumbnail: "https://placehold.co/480x270/1a1a2e/ffffff?text=React+Server+Functions",
    category: "React",
    rank: 36,
    rating: "Great",
  },
];
